### PR TITLE
Create a Dockerfile with `ffmpeg`

### LINKED ISSUE #1: Dockerfile
The task is to create a Dockerfile that builds a container with the ffmpeg package by image and create an entrypoint for it
The explanation may not be perfect yet...

### PR DESCRIPTION
**Pull request by EsterWeiss**
Allows you to use the `ffmpeg` library in a docker image.

Closes #1

### CODE REVIEW

**Comment by bdsoha** [comment]
Please change the readme to include markdown syntax

**Comment by EsterWeiss** [comment]
Did I finish my task?

**Comment by bdsoha** [comment]
> Did I finish my task?

On of the closed PRs, there was a task to run https://github.com/hadolint/hadolint on your docker image.

**Comment by EsterWeiss** [comment]
I did that and fixed all the comments I got on the DockerFile

**Comment by bdsoha** [comment]
**🎉 Congrats on being the first merged PR.**

You will soon be added as a collaborator to this repo.
In the meantime, please prepare a short presentation *(in English)* describing:

- The task in general.
- Things you learned along the way.
- Tips for other team-members for future tasks.

**Comment by bdsoha** [comment]
@EsterWeiss I would also suggesting removing the https://github.com/EsterWeiss/--------- stale repo.

**Comment by bdsoha** [comment]
You have been sent an email invitation to the [SkyVar Organization](https://github.com/skyvar).
Please open your cooperate email and finish the registration process.

**Pull request merged**
