### PR TITLE
Generate RGB histogram from an image

### LINKED ISSUE #7: Numpy
Given an image of choosing, create histogram of RGB colors found in the image using numpy.

### PR DESCRIPTION
**Pull request by RivkaZishinski**
Closes #7

### CODE REVIEW

**Comment by bdsoha** [comment]
Your `main` branch contains the same content *(the actual data)* as the skyvar's `/main`, but the [commit-history](https://github.com/skyvar/registration/pull/16/commits) is different because you deleted and recreated content.

In order to move your `main` branch back in history, you need to run the following command:

```sh
git reset --hard 913dfe2
```
The hash [`913dfe2`](https://github.com/EsterWeiss/registration/commit/913dfe2c88a6e86f232a86304c79cc1b0bd3b7f4) refers to the last commit made in the forked repository. 

After doing so, you will need to do a *force* push:

```sh
git push -f origin main
```

**Comment by RivkaZishinski** [comment]
where to write it?
on command?
if yes -how i direct me to the git ,the git isnt local

**Comment by bdsoha** [comment]
> where to write it? on command? if yes -how i direct me to the git ,the git isnt local

You must always work with a local version of your repository.
Let's start from cloning:

```sh
git clone git@github.com:RivkaZishinski/registration.git
```

**Comment by RivkaZishinski** [comment]
i got Please make sure you have the correct access rights
and the repository exists.

is it better to erase the fork and create new fork

**Comment by bdsoha** [comment]
The simplest way is to start over *(and that is my suggestion for now)*.
In the future, for the learning experience it is good know how `git` works.

**Comment by RivkaZishinski** [comment]
O.K.

**Pull request closed without merging**
