### PR TITLE
Typer

### LINKED ISSUE #12: Typer
`@TODO`

### PR DESCRIPTION
**Pull request by MiriamRotenshtein**
Small CLI app using Typer.

Closes #12

### CODE REVIEW

**Comment by MiriamRotenshtein** [comment]
did you read my code?

**Comment by bdsoha** [comment]
> did you read my code?

I did.
Your task was very similar to @esterlev23 , but instead of using `http` you were told to use the `cli`.
I am going to merge your task as finished because we are short on time.
I'm hoping that the more advance topics that I pointed out to her will be presented to everyone during her presentation.

**Comment by bdsoha** [comment]
**🎉 Congrats on your first merged PR.**

You will soon be added as a collaborator to this repo.
In the meantime, please prepare a short presentation *(in English)* describing:

- The task in general.
- Things you learned along the way.
- Tips for other team-members for future tasks.

**Comment by bdsoha** [comment]
You have been sent an email invitation to the [SkyVar Organization](https://github.com/skyvar).
Please open your cooperate email and finish the registration process.

**Pull request merged**
