### PR TITLE
Create a Dockerfile with `ffmpeg`

### PR DESCRIPTION
**Pull request by EsterWeiss**

### CODE REVIEW

**Comment by bdsoha** [comment]
### Few Cleanup Tasks
- [ ] There can be *merge conflicts* because you did not create a `feature/***` branch from `main`.
- [ ] Do not overwrite content on the `main` branch.
- [ ] Name your repository that same as the *forked* repository.
- [ ] Move your code into a sub-directory.

### Additions
- [ ] Add a description to this PR with a `closes #..` to link the original issue.
- [ ] Add a `README.md` describing how to use/install your code.

**Comment by EsterWeiss** [comment]
Progressing according to the corrections you sent
I started with the Additions
After that I will upload everything again in a good way

**Comment by bdsoha** [comment]
> **Note**
It is considered best practice to either *reply* or add a *reaction* to indicate that you read/understood a given comment.

**Comment by bdsoha** [comment]
**Move your code into a sub-directory.**

Don't overwrite content of the main README.md.

**Comment by EsterWeiss** [comment]
Apparently I still haven't understood enough how the structure should be in git. I tried to create a new branch and there to create pull requests in order to answer the correction: There can be merge conflicts because you did not create a feature/*** branch from main. Am I on the right track?

**Comment by bdsoha** [comment]
First, your file structure should look like this:

```txt
.
├── .github           # <-- Don't touch, it's not yours
├── ffmpeg            # <-- Put your feature code here
│   ├── build.sh
│   ├── Dockerfile
│   └── README.md  
└── README.md         # <-- Don't touch, it's not yours
```

**Comment by bdsoha** [comment]
Second, you need to create a `fork` of the project with the same name as the original project.
Then you need to create a feature-branch on `EsterWeiss/registration`.
Finally, the *PR* is from your feature-branch, back to our main.

**Fork:** `skyvar/registration` ➡ `EsterWeiss/registration`.
**Branch:** `EsterWeiss/registration:main` ➡ `EsterWeiss/registration:feature/ffmpeg`.
**PR:** `EsterWeiss/registration:feature/ffmpeg` 🔀 `skyvar/registration:main`.

**Comment by EsterWeiss** [comment]
Thanks, I'm leaving, I'll finish tomorrow

**Comment by bdsoha** [comment]
Your `main` branch contains the same content *(the actual data)* as the skyvar's `/main`, but the [commit-history](https://github.com/skyvar/registration/pull/16/commits) is different because you deleted and recreated content.

In order to move your `main` branch back in history, you need to run the following command:

```sh
git reset --hard 913dfe2
```
The hash [`913dfe2`](https://github.com/EsterWeiss/registration/commit/913dfe2c88a6e86f232a86304c79cc1b0bd3b7f4) refers to the last commit made in the forked repository.

**Comment by EsterWeiss** [comment]
I am aware of this, because of the confusion I had I thought of rearranging my fork
The next operation is to create a new Branch named feature which will contain the ffmpeg folder containing the files I created
Am I doing it right?

**Comment by bdsoha** [comment]
Your solution code is perfect, just:
- Not located in the right place *(refer to https://github.com/skyvar/registration/pull/16#issuecomment-1469943515)*.
- Your commit history is off, you are not supposed to touch the `main` branch. Deleting and recreating files to mimic the original `main` branch will not help.

**Comment by EsterWeiss** [comment]
I want to make sure I got it right
In order for everything to be correct, I now need to clear the history by commands in cmd,
And actually, you can also delete the old fork and create a new one, and then the history is also clean,

**Comment by bdsoha** [comment]
The simplest way is to start over *(and that is my suggestion for now)*.
In the future, for the learning experience it is good know how `git` works.

**Pull request closed without merging**
