### PR TITLE
Generate RGB histogram from an image

### PR DESCRIPTION
**Pull request by RivkaZishinski**
after clean up

### CODE REVIEW

**Comment by bdsoha** [comment]
@RivkaZishinski 👍 Excellent file PR. Please add a description so that we can move on to the code review.

**Comment by bdsoha** [comment]
Leave the root `README.md` alone *(should be the same as the `main` branch)*.

**Comment by bdsoha** [comment]
> Leave the root `README.md` alone _(should be the same as the `main` branch)_.

Same as before 😞 .

**Comment by RivkaZishinski** [comment]
שמירת התרגום
Because I wrote in the main README, do I have to start deleting and redoing again?

**Comment by bdsoha** [comment]
You can revert changes made in the main `readme` by using `git checkout origin/main README.md`

**Pull request closed without merging**
