### PR TITLE
 FastAPI

### LINKED ISSUE #2: FastAPI
I will create a FastAPI:
Deploy a simple http server with two endpoints:
An endpoint that appends a json payload to a local file.
An endpoint that returns the last 10 payloads from the persisted file.

I will work according to the following guide step by step:
https://fastapi.tiangolo.com/

### PR DESCRIPTION
**Pull request by esterlev23**
## Description

This pull request adds a solution for issue #2, which involved creating a FastAPI application that allows users to retrieve and add user data.

## Changes Made

I have implemented a FastAPI application that includes the following features:

    GET request to retrieve the last 10 users' data
    POST request to add new user data

I have also added Docker support for the application, allowing it to be easily deployed.
Testing Done

I have tested the application locally using `uvicorn` and `docker run`, and was able to successfully retrieve and add user data.

## Related Issues

Closes #2

### CODE REVIEW

**Comment by bdsoha** [comment]
🎉 Great work on being the first PR.

A few cleanup tasks:
- [ ] There are *merge conflicts* because you did not create a `feature/***` branch from `main`.
- [ ] Do not overwrite content on the `main` branch.
- [ ] Name your repository that same as the *forked* repository.

**Comment by bdsoha** [comment]
> **Note**
By changing your description, GitHub was able to relate the issue to the pull request.

```diff
- This pull request closes issue #[2].
+ Closes #2
```

**Comment by esterlev23** [comment]
I got a little confused with the brunch thing.
I'm trying to understand:
What I actually needed was a main branch called Festapi, and also a branch that was mentioned in a description of the project, and this branch to merge it into the main branch?

**Comment by bdsoha** [comment]
No.

You need to create a `fork` of the project with the same name as the original project.
Then you need to create a feature-branch on `esterlev23/registration`.

**Fork:** `skyvar/registration` ➡ `esterlev23/registration`.
**Branch:** `esterlev23/registration:main` ➡ `esterlev23/registration:feature/fast-api`.

**Comment by bdsoha** [comment]
Not exactly:

## Fork repository name
```diff
- esterlev23/Registration
+ esterlev23/registration
# -----------^---------
```

## Main branch
Your repository doesn't have a `main` branch, instead it has `FastAPI` branch.

## PR
Your PR is trying to merge from your main *(name `FastAPI`)* to skyver's main *(named `main`)*.

**Comment by esterlev23** [comment]
I want to delete the fork and create a new one, is this correct?

**Comment by bdsoha** [comment]
> I want to delete the fork and create a new one, is this correct?

That would be the quickest way *(also my suggestion)*.
In the future, when you become more experience with `git` you can utilize a tactic called `cherry-picking` between branches.
For now, save your code somewhere, and refork.

**Pull request closed without merging**
