### PR TITLE
Password strength

### PR DESCRIPTION
**Pull request by FridaPshitik**

### CODE REVIEW

**Comment by bdsoha** [comment]
@FridaPshitik Where is the description to the PR? What is the title?

**Comment by FridaPshitik** [comment]
Everything is good except the title?

**Comment by bdsoha** [comment]
Where is the description to the PR?

Once you provide a description, I will begin the code-review.

**Comment by bdsoha** [comment]
You also are trying to merge from your `main` to skyvar's `main`. You should have created a `feature` branch.

**Comment by FridaPshitik** [comment]
I want to delete such pull requests and it won't let me

**Pull request closed without merging**
